# Generated by Django 5.2.6 on 2025-10-18 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'admin_specialization',
                'ordering': ['specialization_name'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('log_type', models.CharField(choices=[('SUCCESS', 'Successful Login'), ('FAILED', 'Failed Login'), ('LOCKED', 'Account Locked')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'admin_login_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username'], name='admin_login_usernam_73e26f_idx'), models.Index(fields=['log_type'], name='admin_login_log_typ_e8e6dc_idx'), models.Index(fields=['-timestamp'], name='admin_login_timesta_024714_idx')],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('RECEPTIONIST', 'Receptionist'), ('PHARMACIST', 'Pharmacist'), ('LAB_TECHNICIAN', 'Lab Technician')], max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='staff_groups', to='auth.group')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='admin_app.specialization')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='staff_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'admin_staff',
                'ordering': ['staff_name'],
                'indexes': [models.Index(fields=['username'], name='admin_staff_usernam_56689b_idx'), models.Index(fields=['Email'], name='admin_staff_Email_db93db_idx'), models.Index(fields=['role'], name='admin_staff_role_e6688e_idx'), models.Index(fields=['is_active'], name='admin_staff_is_acti_6513ea_idx')],
            },
        ),
    ]
