# Generated by Django 5.2.6 on 2025-10-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('test_description', models.TextField(blank=True, max_length=500)),
                ('test_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'labtech_labtest',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateField(auto_now_add=True)),
                ('result_value', models.TextField(max_length=1000)),
                ('remarks', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='receptionist_app.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labTech_app.labtest')),
            ],
            options={
                'db_table': 'labtech_testresult',
            },
        ),
    ]
