# Generated by Django 5.2.6 on 2025-10-18 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('doctor_app', '0001_initial'),
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('normal_range', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnaround_time', models.CharField(blank=True, help_text='e.g., 24 hours', max_length=100)),
                ('sample_type', models.CharField(blank=True, help_text='e.g., Blood, Urine', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'labtech_lab_tests',
                'ordering': ['test_name'],
                'indexes': [models.Index(fields=['is_active'], name='labtech_lab_is_acti_9b76a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateField(default=django.utils.timezone.now)),
                ('result_value', models.TextField(blank=True)),
                ('result_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('is_normal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='doctor_app.consultation')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labTech_app.labtest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='receptionist_app.patient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_tests', to='admin_app.staff')),
            ],
            options={
                'db_table': 'labtech_test_results',
                'ordering': ['-test_date'],
                'indexes': [models.Index(fields=['result_status'], name='labtech_tes_result__1ab42c_idx'), models.Index(fields=['test_date'], name='labtech_tes_test_da_4bebfd_idx')],
            },
        ),
    ]
