# Generated by Django 5.2.6 on 2025-10-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labTech_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='high_range',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='low_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='unit',
            field=models.CharField(default='mg/dL', max_length=50),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
