# Generated by Django 5.2.6 on 2025-10-18 07:09

import django.db.models.deletion
import doctor_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_date', models.DateField(default=doctor_app.models.get_today_date)),
                ('consultation_time', models.TimeField(auto_now_add=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='receptionist_app.appointment')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='admin_app.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='receptionist_app.patient')),
            ],
            options={
                'db_table': 'doctor_consultations',
                'ordering': ['-consultation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_date', models.DateField(default=doctor_app.models.get_today_date)),
                ('general_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor_app.consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='admin_app.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='receptionist_app.patient')),
            ],
            options={
                'db_table': 'doctor_prescriptions',
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('medicine_prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('OD', 'Once Daily'), ('BD', 'Twice Daily'), ('TDS', 'Three Times Daily'), ('QID', 'Four Times Daily'), ('SOS', 'As Needed')], max_length=10)),
                ('timing', models.CharField(blank=True, choices=[('BEFORE_FOOD', 'Before Food'), ('AFTER_FOOD', 'After Food'), ('WITH_FOOD', 'With Food'), ('EMPTY_STOMACH', 'Empty Stomach')], max_length=20)),
                ('duration', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='doctor_app.prescription')),
            ],
            options={
                'db_table': 'doctor_medicine_prescriptions',
            },
        ),
        migrations.CreateModel(
            name='TestPrescription',
            fields=[
                ('test_prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='doctor_app.prescription')),
            ],
            options={
                'db_table': 'doctor_test_prescriptions',
            },
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='doctor_cons_status_531b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor', 'consultation_date'], name='doctor_cons_doctor__c8ff06_idx'),
        ),
    ]
