# Generated by Django 5.2.6 on 2025-10-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_date', models.DateField(auto_now_add=True)),
                ('symptoms', models.CharField(max_length=500)),
                ('diagnosis', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='receptionist_app.appointment')),
            ],
            options={
                'db_table': 'doctor_consultation',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_date', models.DateField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor_app.consultation')),
            ],
            options={
                'db_table': 'doctor_prescription',
            },
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('medicine_prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True, max_length=500)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='doctor_app.prescription')),
            ],
            options={
                'db_table': 'doctor_medicine_prescription',
            },
        ),
        migrations.CreateModel(
            name='TestPrescription',
            fields=[
                ('test_prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('instructions', models.CharField(blank=True, max_length=500, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='doctor_app.prescription')),
            ],
            options={
                'db_table': 'doctor_test_prescription',
            },
        ),
    ]
