<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-19 06:57

import django.db.models.deletion
=======
# Generated by Django 5.2.6 on 2025-09-19 04:46

import django.db.models.deletion
from django.conf import settings
>>>>>>> d0a3139415147984e556c3b9d6da1fd6eafb3b64
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('admin_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> d0a3139415147984e556c3b9d6da1fd6eafb3b64
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
=======
            name='Appointment',
            fields=[
                ('AppointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentDate', models.DateTimeField()),
                ('Reason', models.CharField(max_length=200)),
                ('Doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.doctor')),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> d0a3139415147984e556c3b9d6da1fd6eafb3b64
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Patient_name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
<<<<<<< HEAD
                ('Gender', models.CharField(max_length=20)),
                ('Blood_Group', models.CharField(max_length=5)),
                ('Address', models.CharField(max_length=200)),
                ('Phone_number', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Appointment_date', models.DateField(auto_now_add=True)),
                ('Appointment_time', models.TimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.doctor')),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Generation',
            fields=[
                ('Bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Billing_date', models.DateField(auto_now_add=True)),
                ('Token', models.CharField(max_length=20, unique=True)),
                ('Appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.appointment')),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patient')),
=======
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=15)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> d0a3139415147984e556c3b9d6da1fd6eafb3b64
            ],
        ),
    ]
