# Generated by Django 5.2.6 on 2025-10-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Patient_name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Blood_Group', models.CharField(max_length=5)),
                ('Address', models.CharField(max_length=200)),
                ('Phone_number', models.CharField(max_length=15)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Appointment_date', models.DateField()),
                ('Appointment_time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('booked', 'booked'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='booked', max_length=20)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='admin_app.staff')),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='receptionist_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Generation',
            fields=[
                ('Bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Billing_date', models.DateField(auto_now_add=True)),
                ('Token', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='receptionist_app.appointment')),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='receptionist_app.patient')),
            ],
        ),
    ]
