# Generated by Django 5.2.6 on 2025-09-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='booked', max_length=20),
        ),
    ]
