# Generated by Django 5.2.6 on 2025-10-16 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Age',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 10, 16)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='receptionist_appointment',
        ),
        migrations.AlterModelTable(
            name='bill_generation',
            table='receptionist_bill_generation',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='receptionist_patient',
        ),
    ]
