# Generated by Django 5.2.6 on 2025-09-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='User',
        ),
    ]
