# Generated by Django 5.2.6 on 2025-09-19 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_app', '0002_remove_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patient'),
        ),
    ]
