# Generated by Django 5.2.6 on 2025-09-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacist_medicine',
            fields=[
                ('MedicineId', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
