# Generated by Django 5.2.6 on 2025-10-18 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Categories',
                'db_table': 'pharmacist_medicine_categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('expiry_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_medicines', to='admin_app.staff')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='pharmacist_app.medicinecategory')),
            ],
            options={
                'db_table': 'pharmacist_medicines',
                'ordering': ['medicine_name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('movement_id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('RETURN', 'Return'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('movement_date', models.DateField(default=django.utils.timezone.now)),
                ('movement_time', models.TimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='pharmacist_app.medicine')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='admin_app.staff')),
            ],
            options={
                'db_table': 'pharmacist_stock_movements',
                'ordering': ['-movement_date', '-movement_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacist_app.medicine')),
            ],
            options={
                'db_table': 'pharmacist_medicine_batches',
                'ordering': ['-expiry_date'],
                'unique_together': {('medicine', 'batch_number')},
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['medicine_name'], name='pharmacist__medicin_aba698_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_active'], name='pharmacist__is_acti_e46b21_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['expiry_date'], name='pharmacist__expiry__87554e_idx'),
        ),
    ]
