# Generated by Django 5.2.6 on 2025-09-18 07:24

import django.core.validators
import django.db.models.deletion
import pharmacist_app.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (minimum 3 characters)', max_length=100, unique=True, validators=[pharmacist_app.models.validate_medicine_name])),
                ('description', models.TextField(blank=True, help_text='Optional category description', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Is this category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Categories',
                'db_table': 'pharmacist_medicine_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_code', models.CharField(blank=True, help_text='Auto-generated prescription code', max_length=20, unique=True)),
                ('patient_name', models.CharField(help_text='Patient full name', max_length=200, validators=[pharmacist_app.models.validate_medicine_name])),
                ('patient_phone', models.CharField(help_text='Patient 10-digit phone number', max_length=15, validators=[pharmacist_app.models.validate_phone_number])),
                ('patient_age', models.PositiveIntegerField(help_text='Patient age in years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('doctor_name', models.CharField(help_text='Prescribing doctor name', max_length=200, validators=[pharmacist_app.models.validate_medicine_name])),
                ('prescription_date', models.DateTimeField(auto_now_add=True, help_text='Date prescription was created')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_DISPENSED', 'Partially Dispensed'), ('FULLY_DISPENSED', 'Fully Dispensed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Prescription status', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total prescription amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'db_table': 'pharmacist_prescription',
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier company name', max_length=200, unique=True, validators=[pharmacist_app.models.validate_company_name])),
                ('contact_person', models.CharField(help_text='Primary contact person', max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Contact person name must be at least 3 characters.'), django.core.validators.RegexValidator(message='Contact person name can only contain letters, spaces, and periods.', regex='^[A-Za-z\\s\\.]+$')])),
                ('phone', models.CharField(help_text='10-digit contact number', max_length=15, unique=True, validators=[pharmacist_app.models.validate_phone_number])),
                ('email', models.EmailField(help_text='Contact email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('address', models.TextField(help_text='Complete business address', max_length=500, validators=[django.core.validators.MinLengthValidator(10, 'Address must be at least 10 characters.')])),
                ('is_active', models.BooleanField(default=True, help_text='Is this supplier active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pharmacist_supplier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_code', models.CharField(blank=True, help_text='Auto-generated medicine code', max_length=20, unique=True)),
                ('medicine_name', models.CharField(db_index=True, help_text='Brand name of medicine (minimum 3 characters)', max_length=200, validators=[pharmacist_app.models.validate_medicine_name])),
                ('generic_name', models.CharField(blank=True, help_text='Generic/chemical name', max_length=200, validators=[pharmacist_app.models.validate_generic_name])),
                ('company_name', models.CharField(help_text='Manufacturing company name', max_length=200, validators=[pharmacist_app.models.validate_company_name])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[pharmacist_app.models.validate_positive_price])),
                ('total_quantity', models.PositiveIntegerField(default=0, help_text='Total quantity in stock (sum of all batches)', validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Minimum stock level before reorder alert', validators=[django.core.validators.MinValueValidator(1, 'Reorder level must be at least 1.'), django.core.validators.MaxValueValidator(1000, 'Reorder level cannot exceed 1000.')])),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('OINTMENT', 'Ointment')], default='TABLET', help_text='Medicine form/type', max_length=50)),
                ('strength', models.CharField(blank=True, help_text='Medicine strength (e.g., 500mg, 10ml)', max_length=50)),
                ('is_prescription_required', models.BooleanField(default=True, help_text='Is prescription required?')),
                ('is_active', models.BooleanField(default=True, help_text='Is medicine active? (as per PDF disable functionality)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Medicine category', on_delete=django.db.models.deletion.PROTECT, to='pharmacist_app.medicinecategory')),
            ],
            options={
                'db_table': 'pharmacist_medicine',
                'ordering': ['medicine_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Batch/lot number', max_length=50, validators=[pharmacist_app.models.validate_batch_number])),
                ('quantity_received', models.PositiveIntegerField(help_text='Initial quantity received', validators=[pharmacist_app.models.validate_positive_quantity])),
                ('quantity_available', models.PositiveIntegerField(help_text='Current available quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost price per unit', max_digits=10, validators=[pharmacist_app.models.validate_positive_price])),
                ('expiry_date', models.DateField(help_text='Medicine expiry date', validators=[pharmacist_app.models.validate_expiry_date])),
                ('manufacturing_date', models.DateField(blank=True, help_text='Manufacturing date', null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True, help_text='Date when stock was received')),
                ('is_damaged', models.BooleanField(default=False, help_text='Is this batch damaged?')),
                ('damage_notes', models.TextField(blank=True, help_text='Notes about damage (if any)', max_length=500)),
                ('medicine', models.ForeignKey(help_text='Associated medicine', on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='pharmacist_app.medicine')),
                ('supplier', models.ForeignKey(help_text='Medicine supplier', on_delete=django.db.models.deletion.PROTECT, to='pharmacist_app.supplier')),
            ],
            options={
                'db_table': 'pharmacist_medicine_stock',
                'ordering': ['expiry_date', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_prescribed', models.PositiveIntegerField(help_text='Quantity prescribed by doctor', validators=[pharmacist_app.models.validate_positive_quantity])),
                ('quantity_dispensed', models.PositiveIntegerField(default=0, help_text='Quantity already dispensed', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of prescription', max_digits=10, validators=[pharmacist_app.models.validate_positive_price])),
                ('dosage_instructions', models.TextField(help_text='How to take the medicine', max_length=500)),
                ('medicine', models.ForeignKey(help_text='Prescribed medicine', on_delete=django.db.models.deletion.PROTECT, to='pharmacist_app.medicine')),
                ('prescription', models.ForeignKey(help_text='Associated prescription', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacist_app.prescription')),
            ],
            options={
                'db_table': 'pharmacist_prescription_item',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_code', models.CharField(blank=True, help_text='Auto-generated sale code', max_length=20, unique=True)),
                ('customer_name', models.CharField(help_text='Customer name', max_length=200, validators=[pharmacist_app.models.validate_medicine_name])),
                ('customer_phone', models.CharField(help_text='Customer phone number', max_length=15, validators=[pharmacist_app.models.validate_phone_number])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before tax and discount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final total amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('INSURANCE', 'Insurance')], default='CASH', help_text='Payment method used', max_length=20)),
                ('is_completed', models.BooleanField(default=False, help_text='Is sale completed?')),
                ('sale_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of sale')),
                ('pharmacist', models.ForeignKey(help_text='Pharmacist who processed the sale', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, help_text='Associated prescription (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacist_app.prescription')),
            ],
            options={
                'db_table': 'pharmacist_sale',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity sold', validators=[pharmacist_app.models.validate_positive_quantity])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of sale', max_digits=10, validators=[pharmacist_app.models.validate_positive_price])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Line item subtotal', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('medicine', models.ForeignKey(help_text='Medicine sold', on_delete=django.db.models.deletion.PROTECT, to='pharmacist_app.medicine')),
                ('sale', models.ForeignKey(help_text='Associated sale', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacist_app.sale')),
                ('stock_batch', models.ForeignKey(help_text='Stock batch used', on_delete=django.db.models.deletion.PROTECT, to='pharmacist_app.medicinestock')),
            ],
            options={
                'db_table': 'pharmacist_sale_item',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired Stock'), ('DAMAGED', 'Damaged Stock')], help_text='Type of alert', max_length=20)),
                ('message', models.TextField(help_text='Alert message', max_length=500)),
                ('is_resolved', models.BooleanField(default=False, help_text='Has this alert been resolved?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('medicine', models.ForeignKey(help_text='Medicine with alert', on_delete=django.db.models.deletion.CASCADE, to='pharmacist_app.medicine')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_batch', models.ForeignKey(blank=True, help_text='Specific stock batch (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacist_app.medicinestock')),
            ],
            options={
                'db_table': 'pharmacist_stock_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('medicine_name', 'company_name', 'strength'), name='unique_medicine_combination'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='positive_unit_price'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('total_quantity__gte', 0)), name='non_negative_quantity'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.UniqueConstraint(fields=('prescription', 'medicine'), name='unique_medicine_per_prescription'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_dispensed__lte', models.F('quantity_prescribed'))), name='dispensed_lte_prescribed'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='positive_total_amount'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gt', 0)), name='positive_item_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='medicinestock',
            constraint=models.UniqueConstraint(fields=('medicine', 'batch_number', 'supplier'), name='unique_batch_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='medicinestock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__lte', models.F('quantity_received'))), name='available_lte_received'),
        ),
        migrations.AddConstraint(
            model_name='medicinestock',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gt', 0)), name='positive_unit_cost'),
        ),
    ]
